# Documentation: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
channel = "nightly-2026-02-20"
components = ["rustfmt", "clippy", "llvm-tools", "rustc-dev", "rust-src"]
